//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioAutomacaoApiRest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DesafioAutomacaoApiRest")]
        public string REPORT_NAME {
            get {
                return ((string)(this["REPORT_NAME"]));
            }
            set {
                this["REPORT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.99.100:8989")]
        public string QA_URL {
            get {
                return ((string)(this["QA_URL"]));
            }
            set {
                this["QA_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62gHUwBfmIrh2IAMpEvv13u_u4HEpKIU")]
        public string QA_TOKEN {
            get {
                return ((string)(this["QA_TOKEN"]));
            }
            set {
                this["QA_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int REPORT_SUBSTRING_LENGTH {
            get {
                return ((int)(this["REPORT_SUBSTRING_LENGTH"]));
            }
            set {
                this["REPORT_SUBSTRING_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.99.100")]
        public string QA_DB_SERVER {
            get {
                return ((string)(this["QA_DB_SERVER"]));
            }
            set {
                this["QA_DB_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bugtracker")]
        public string QA_DB_NAME {
            get {
                return ((string)(this["QA_DB_NAME"]));
            }
            set {
                this["QA_DB_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string QA_DB_USER {
            get {
                return ((string)(this["QA_DB_USER"]));
            }
            set {
                this["QA_DB_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string QA_DB_PASSWORD {
            get {
                return ((string)(this["QA_DB_PASSWORD"]));
            }
            set {
                this["QA_DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string DB_CONNECTION_TIMEOUT {
            get {
                return ((string)(this["DB_CONNECTION_TIMEOUT"]));
            }
            set {
                this["DB_CONNECTION_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usuarioAuthentication")]
        public string QA_AUTHENTICATOR_USER {
            get {
                return ((string)(this["QA_AUTHENTICATOR_USER"]));
            }
            set {
                this["QA_AUTHENTICATOR_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("senhaAuthentication")]
        public string QA_AUTHENTICATOR_PASSWORD {
            get {
                return ((string)(this["QA_AUTHENTICATOR_PASSWORD"]));
            }
            set {
                this["QA_AUTHENTICATOR_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string QA_DB_PORT {
            get {
                return ((string)(this["QA_DB_PORT"]));
            }
            set {
                this["QA_DB_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DEV_DB_PORT {
            get {
                return ((string)(this["DEV_DB_PORT"]));
            }
            set {
                this["DEV_DB_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.99.100")]
        public string DEV_DB_SERVER {
            get {
                return ((string)(this["DEV_DB_SERVER"]));
            }
            set {
                this["DEV_DB_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62gHUwBfmIrh2IAMpEvv13u_u4HEpKIU")]
        public string DEV_TOKEN {
            get {
                return ((string)(this["DEV_TOKEN"]));
            }
            set {
                this["DEV_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.99.100:8989")]
        public string DEV_URL {
            get {
                return ((string)(this["DEV_URL"]));
            }
            set {
                this["DEV_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DEV_DB_USER {
            get {
                return ((string)(this["DEV_DB_USER"]));
            }
            set {
                this["DEV_DB_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qa")]
        public string ENVIRONMENT {
            get {
                return ((string)(this["ENVIRONMENT"]));
            }
            set {
                this["ENVIRONMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bugtracker")]
        public string DEV_DB_NAME {
            get {
                return ((string)(this["DEV_DB_NAME"]));
            }
            set {
                this["DEV_DB_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DEV_DB_PASSWORD {
            get {
                return ((string)(this["DEV_DB_PASSWORD"]));
            }
            set {
                this["DEV_DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("senhaAuthentication")]
        public string DEV_AUTHENTICATOR_PASSWORD {
            get {
                return ((string)(this["DEV_AUTHENTICATOR_PASSWORD"]));
            }
            set {
                this["DEV_AUTHENTICATOR_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usuarioAuthentication")]
        public string DEV_AUTHENTICATOR_USER {
            get {
                return ((string)(this["DEV_AUTHENTICATOR_USER"]));
            }
            set {
                this["DEV_AUTHENTICATOR_USER"] = value;
            }
        }
    }
}
